### PR TITLE
Updates for Google style guide.

### PR DESCRIPTION
**Pull request by jawalonoski**
- Added checkstyle to the build, using the Google Java style guide.
- Enabled checkstyle and sonar on code climate.
- Reformatted the existing code to fit the checkstyle guide.

### CODE REVIEW

**Comment by jawalonoski** [comment]
Executing `./gradlew check` shows no issues with checkstyle, so I'm not sure what code climate is complaining about... I'll have to investigate.

**Comment by dehall** [comment]
My only concern here is the upcoming merge conflicts given that we have 3 other active code branches. Not sure whether they would be less painful if this gets merged first or last.

**Comment by jawalonoski** [comment]
Yes, it will be painful. Better to just get it over with... still in works. Need to add Javadoc comments to every method.

**Comment by jawalonoski** [comment]
Rebased this mess. Hopefully I got it correct.

**Comment by jawalonoski** [comment]
At this point, the remaining issues are related to missing javadoc comments. There are a lot missing. We can either:
1. choose to disable this requirement, 
2. spend the time to add comments to hundreds of methods, or 
3. auto-generate comments. 

The last option is sort of like pollution, since auto-generated comments tend to use space without adding value. The second option is clearly the best, but it will take a lot of time.

**Comment by dehall** [comment]
No auto-generated comments. Those are really worse than no comments because they don't say anything the code doesn't already say, and with no code warning nobody would ever improve it.

My vote is reduce the severity level to warning and add comments as we continue to move forward. Instead of adding them all at once here, we require all new methods to have comments, and anytime we modify a method we add the missing comments.

**Comment by jawalonoski** [comment]
I tend to agree. I'll change the severity level.

**Comment by jawalonoski** [comment]
Not sure why code climate reports 433 issues. My local copy reports nothing but warnings now...

**Comment by jawalonoski** [comment]
I can't figure out what code climate is doing, and it's reporting on branches/pull requests sucks, so I'm dropping it.

**Comment by dehall** [comment]
Do you still want to consider using codeclimate in the future? If not can you delete the .codeclimate.yml file?

**Pull request merged**
