### PR TITLE
CSV and Text exporters

### PR DESCRIPTION
**Pull request by dehall**
Re-introduces the CSV and human-readable text exporter formats.

Sample text record:
[Mary Smith_f7cd9b99-9286-4555-ba90-149e93317c4c.txt](https://github.com/synthetichealth/synthea_java/files/1454936/Mary.Smith_f7cd9b99-9286-4555-ba90-149e93317c4c.txt)

Sample CSVs (renamed to TXT for github):
[patients.csv.txt](https://github.com/synthetichealth/synthea_java/files/1454930/patients.csv.txt)
[conditions.csv.txt](https://github.com/synthetichealth/synthea_java/files/1454931/conditions.csv.txt)

### CODE REVIEW

**Comment by jawalonoski** [comment]
The sample CSV files have trailing commas on each line, but they should not.

Also, the `DEATHDATE` column seems to have a space (`, ,`) on null values... this space should probably not be there (e.g. `,,`)

**Comment by jawalonoski** [comment]
As for the text record, if there are no allergies, please print `No Known Allergies`... I know the Ruby version does not do this, but it should.

**Comment by dehall** [comment]
Updated samples: 
[Zackery Bernier_fa7ea11e-1407-4ece-9cdf-934f4dc9ae24.txt](https://github.com/synthetichealth/synthea_java/files/1471130/Zackery.Bernier_fa7ea11e-1407-4ece-9cdf-934f4dc9ae24.txt)

[patients.csv.txt](https://github.com/synthetichealth/synthea_java/files/1471124/patients.csv.txt)

[conditions.csv.txt](https://github.com/synthetichealth/synthea_java/files/1471125/conditions.csv.txt)

**Comment by jawalonoski** [comment]
You still have a space in the conditions stop date when it is missing.... `, ,` but should be `,,`

**Comment by dehall** [comment]
Ok. Updated one more time to remove the space in the stop dates. (It wasn't just conditions it was anything with a stop date)

New sample files:

[immunizations.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474673/immunizations.csv.txt)
[medications.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474674/medications.csv.txt)
[observations.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474675/observations.csv.txt)
[patients.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474676/patients.csv.txt)
[procedures.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474677/procedures.csv.txt)
[allergies.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474678/allergies.csv.txt)
[careplans.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474679/careplans.csv.txt)
[conditions.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474680/conditions.csv.txt)
[encounters.csv.txt](https://github.com/synthetichealth/synthea_java/files/1474681/encounters.csv.txt)

(note that allergies is always empty at the moment because of a separate issue with submodules which I'll address with a PR in the next few days)

**Pull request merged**
