### PR TITLE
Fhir export + Patient locations + Converted ruby module skeletons

### PR DESCRIPTION
**Pull request by dehall**
This is no more feature-complete than anything else on this repo yet. But it's a working baseline to fill in details as needed.

Adds:

- A standard java properties file (I know, ugly compared to YAML but requires no additional dependencies)
- A FHIR exporter, using HAPI FHIR to export patients to a configurable directory.
- People have names & addresses, via Faker, and a geographic location
- skeletons of the Lifecycle and Cardiovascular Disease module, which extend the Module class and provide overridden implementations of the process() method.

### CODE REVIEW

**Comment by jawalonoski** [comment]
One change requested: `Person` has a seeded `Random` built in. Please use that one all `next####()` calls. The idea is so that we should be able to rerun the exact same person repeatedly.

**Comment by jawalonoski** [comment]
Perhaps we should setup continuous integration, because this doesn't compile for me.

```
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find jai_core.jar (javax.media:jai_core:1.1.3)
```

Apparently this is a known issue with geo tools that this dependency can't be distributed. Not sure it has a place in this open-source project.

**Comment by dehall** [comment]
Oh it looks like I didn't see that error because I've been running from my IDE and not via gradle. The code doesn't actually require whatever is in that jar. I'll see if there's a workaround, or if not it shouldn't be too hard to replace with another GeoJSON library, maybe this one: https://github.com/opendatalab-de/geojson-jackson

**Comment by dehall** [comment]
@jawalonoski addressed comments - all random calls now use Person.rand, and replaced the GeoTools library with JTS and another library to convert to JTS.

**Pull request merged**
